remote_theme: thelehhman/texture

# Dependencies
highlighter:      rouge
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-github-metadata

permalink: pretty

