theme: jekyll-theme-leap-day

# Dependencies
highlighter:      rouge
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  
permalink: pretty

