remote_theme: thelehhman/texture

# Dependencies
highlighter:      rouge
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-github-metadata

defaults:
  - scope:
      path: ""
      type: wiki
    values:
      layout: default
      permalink: /:collection/:path

